import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/course.dart';

final courseProvider = Provider<List<Course>>((ref) {
  return [
    Course(
      title: "AutoCAD 2D & 3D Design",
      slug: "autocad-2d-3d-design",
      description: "Master industry-standard AutoCAD tools for precise 2D drafting and 3D modeling essential for architects, engineers, and designers. This comprehensive course covers everything from basic drawing commands to advanced 3D visualization techniques used in real construction and manufacturing projects.",
      imageUrl: "https://www.nlitedu.com/fontimage/autocad.png",
      category: "DESIGN",
      categoryColor: Colors.orange,
      duration: "12 Weeks",
      level: "Intermediate",
      rating: 4.9,
      price: "₹999*",
      isBestseller: true,
      highlights: [
        "2D Drafting and 3D Modeling",
        "Industry-standard AutoCAD workflow",
        "Project-based learning for real-world design",
        "Layout, annotation, and dimensioning",
        "Live internship project included",
        "Industry-recognized NLIT certification",
      ],
      instructorName: "Ar. Rahul Sharma",
      instructorImage: "https://ui-avatars.com/api/?name=Rahul+Sharma&background=6366f1&color=fff&format=png",
      totalReviews: 1250,
      syllabus: [
        "Introduction to AutoCAD Interface & Navigation",
        "Drawing & Modification Tools (Line, Arc, Trim, Fillet)",
        "Layers, Blocks & Hatching",
        "Dimensioning & Annotations",
        "3D Modeling: Wireframe, Surface & Solid",
        "Rendering & Visualization",
        "Plotting & Layout Setup",
        "Live Project: Architectural Floor Plan",
      ],
    ),
    Course(
      title: "Revit Building Information Modeling (BIM)",
      slug: "revit-bim",
      description: "Learn BIM workflows and Revit software to create collaborative building designs with real-world applications. Gain hands-on skills in architectural, structural and MEP modeling that industry employers demand.",
      imageUrl: "https://www.nlitedu.com/fontimage/revit.jpg",
      category: "DESIGN",
      categoryColor: Colors.orange,
      duration: "12 Weeks",
      level: "Intermediate",
      rating: 4.8,
      price: "₹999*",
      highlights: [
        "BIM modeling and collaboration",
        "Architecture, structure, and MEP support",
        "Live project-based Revit exercises",
        "Clash detection & coordination",
        "Industry-recognized NLIT certification",
        "Real-world construction documentation",
      ],
      instructorName: "Er. Amit Singh",
      instructorImage: "https://ui-avatars.com/api/?name=Amit+Singh&background=6366f1&color=fff&format=png",
      totalReviews: 850,
      syllabus: [
        "BIM Concepts & Revit Interface",
        "Walls, Doors, Windows & Components",
        "Floor Plans & Elevations",
        "Structural Modeling & Foundations",
        "MEP Systems (Mechanical/Electrical/Plumbing)",
        "Scheduling & Quantities",
        "Rendering & Walkthroughs",
        "Live Project: Residential Building Model",
      ],
    ),
    Course(
      title: "Java Programming",
      slug: "java-programming",
      description: "Develop robust enterprise-level applications by mastering Java fundamentals and advanced programming concepts. From OOP to multithreading, build real-world apps that solve complex business problems.",
      imageUrl: "https://www.nlitedu.com/fontimage/java.png",
      category: "PROGRAMMING",
      categoryColor: Colors.red,
      duration: "16 Weeks",
      level: "Advanced",
      rating: 4.8,
      price: "₹999*",
      isBestseller: true,
      highlights: [
        "Core Java fundamentals & OOP",
        "Object-oriented design and data structures",
        "Build real applications with practical examples",
        "Multithreading & exception handling",
        "JDBC & database connectivity",
        "Industry-recognized NLIT certification",
      ],
      instructorName: "Sanjay Kumar",
      instructorImage: "https://ui-avatars.com/api/?name=Sanjay+Kumar&background=ef4444&color=fff&format=png",
      totalReviews: 2100,
      syllabus: [
        "Java Basics & Syntax",
        "OOP — Classes, Objects, Inheritance",
        "Polymorphism & Abstraction",
        "Exception Handling & File I/O",
        "Collections Framework",
        "Multithreading & Concurrency",
        "JDBC & Database Integration",
        "Capstone: Full-Stack Java App",
      ],
    ),
    Course(
      title: "Python for Data Science & AI",
      slug: "python-data-science-ai",
      description: "Dive into Python programming with a focus on data analysis, AI, and machine learning applications. Learn to transform raw data into actionable insights using industry-standard libraries and frameworks.",
      imageUrl: "https://www.nlitedu.com/fontimage/python.png",
      category: "DATA SCIENCE",
      categoryColor: Colors.blue,
      duration: "10 Weeks",
      level: "Beginner",
      rating: 4.7,
      price: "₹999*",
      highlights: [
        "Python programming for analytics",
        "Data visualization and machine learning",
        "Hands-on AI use cases with Python",
        "NumPy, Pandas & Matplotlib mastery",
        "Scikit-learn for ML models",
        "Industry-recognized NLIT certification",
      ],
      instructorName: "Dr. Anita Rao",
      instructorImage: "https://ui-avatars.com/api/?name=Anita+Rao&background=3b82f6&color=fff&format=png",
      totalReviews: 1800,
      syllabus: [
        "Python Fundamentals & Environment Setup",
        "Data Types, Control Flow & Functions",
        "NumPy for Numerical Computing",
        "Pandas for Data Manipulation",
        "Data Visualization with Matplotlib & Seaborn",
        "Intro to Machine Learning with Scikit-learn",
        "Regression & Classification Models",
        "Capstone: AI-Powered Data Analysis",
      ],
    ),
    Course(
      title: "Python Programming",
      slug: "python-programming",
      description: "Master Python for data science, scripting, and automation with hands-on programming practice. Build practical projects from web scraping to task automation that give you an industry edge.",
      imageUrl: "https://www.nlitedu.com/fontimage/python.png",
      category: "PROGRAMMING",
      categoryColor: Colors.red,
      duration: "8 Weeks",
      level: "Beginner",
      rating: 4.6,
      price: "₹999*",
      highlights: [
        "Python fundamentals and scripting",
        "Data processing and automation",
        "Build practical Python projects",
        "File handling & error management",
        "Web scraping basics",
        "Industry-recognized NLIT certification",
      ],
      instructorName: "Vikas Gupta",
      instructorImage: "https://ui-avatars.com/api/?name=Vikas+Gupta&background=ef4444&color=fff&format=png",
      totalReviews: 1200,
      syllabus: [
        "Python Syntax & Variables",
        "Control Flow & Loops",
        "Functions & Modules",
        "File I/O & Exception Handling",
        "OOP in Python",
        "Working with Libraries (os, sys, json)",
        "Web Scraping & APIs",
        "Capstone: Automation Project",
      ],
    ),
    Course(
      title: "MATLAB for Scientific Computing",
      slug: "matlab-scientific-computing",
      description: "Gain critical skills in MATLAB for data analysis, control systems, and engineering computations. Master signal processing, simulation, and numerical methods used across engineering disciplines.",
      imageUrl: "https://www.nlitedu.com/fontimage/matlab2.png",
      category: "ENGINEERING",
      categoryColor: Colors.blue,
      duration: "8 Weeks",
      level: "Intermediate",
      rating: 4.6,
      price: "₹999*",
      highlights: [
        "MATLAB for engineering workflows",
        "Simulation and numerical computing",
        "Data analysis with MATLAB toolboxes",
        "Signal processing & control systems",
        "Simulink modeling",
        "Industry-recognized NLIT certification",
      ],
      instructorName: "Kiran Mazumdar",
      instructorImage: "https://ui-avatars.com/api/?name=Kiran+Mazumdar&background=3b82f6&color=fff&format=png",
      totalReviews: 650,
      syllabus: [
        "MATLAB Environment & Basics",
        "Matrices, Arrays & Operators",
        "Plotting & Data Visualization",
        "Script & Function Files",
        "Simulink Introduction",
        "Signal Processing Toolbox",
        "Control System Analysis",
        "Final Project: Engineering Simulation",
      ],
    ),
    Course(
      title: "STAAD Pro",
      slug: "staadpro",
      description: "Learn advanced structural analysis and design using STAAD Pro for civil and structural engineering. Design real-world structures with industry-standard load combinations and code-based checks.",
      imageUrl: "https://www.nlitedu.com/fontimage/staadpro.jpg",
      category: "ENGINEERING",
      categoryColor: Colors.blue,
      duration: "10 Weeks",
      level: "Advanced",
      rating: 4.5,
      price: "₹999*",
      highlights: [
        "Structural modeling and analysis",
        "Load case simulation & combinations",
        "Design optimization for real-world structures",
        "IS code-based design checks",
        "RCC & Steel design",
        "Industry-recognized NLIT certification",
      ],
      instructorName: "Arun Prajapati",
      instructorImage: "https://ui-avatars.com/api/?name=Arun+Prajapati&background=3b82f6&color=fff&format=png",
      totalReviews: 450,
      syllabus: [
        "STAAD Pro Interface & Setup",
        "Node, Beam & Plate Modeling",
        "Material & Section Properties",
        "Load Types & Combinations",
        "Running Analysis & Results",
        "RCC Design Module",
        "Steel Design Module",
        "Capstone: Multi-Story Building Design",
      ],
    ),
    Course(
      title: "SolidWorks",
      slug: "solidworks",
      description: "Master mechanical design, simulation, and product development using SolidWorks CAD. Create manufacturing-ready 3D models and assemblies used in automotive, aerospace, and consumer products.",
      imageUrl: "https://www.nlitedu.com/fontimage/solid2.png",
      category: "DESIGN",
      categoryColor: Colors.orange,
      duration: "12 Weeks",
      level: "Advanced",
      rating: 4.7,
      price: "₹999*",
      highlights: [
        "3D mechanical design & part modeling",
        "Assembly modeling and simulation",
        "Manufacturing-ready product design",
        "Sheet metal & weldment features",
        "Motion study & stress analysis",
        "Industry-recognized NLIT certification",
      ],
      instructorName: "Rakesh Kumar",
      instructorImage: "https://ui-avatars.com/api/?name=Rakesh+Kumar&background=f97316&color=fff&format=png",
      totalReviews: 540,
      syllabus: [
        "SolidWorks Interface & Sketching",
        "Part Modeling (Extrude, Revolve, Loft)",
        "Assembly Design & Mates",
        "Drawing & Detailing",
        "Sheet Metal Design",
        "Surface Modeling",
        "Simulation & Stress Analysis",
        "Capstone: Product Design Project",
      ],
    ),
    Course(
      title: "CATIA",
      slug: "catia",
      description: "Explore advanced CAD/CAM workflows with CATIA for automotive, aerospace, and industrial design. Master Dassault Systèmes' flagship software used by BMW, Boeing, and global engineering leaders.",
      imageUrl: "https://www.nlitedu.com/fontimage/CATI2.png",
      category: "DESIGN",
      categoryColor: Colors.orange,
      duration: "14 Weeks",
      level: "Advanced",
      rating: 4.8,
      price: "₹999*",
      highlights: [
        "Advanced surface modeling",
        "CAD/CAM integration",
        "Industry-standard product design techniques",
        "Generative shape design",
        "Assembly design & kinematics",
        "Industry-recognized NLIT certification",
      ],
      instructorName: "Sandeep Yadav",
      instructorImage: "https://ui-avatars.com/api/?name=Sandeep+Yadav&background=f97316&color=fff&format=png",
      totalReviews: 320,
      syllabus: [
        "CATIA Interface & Part Design",
        "Sketcher & Constraint-based Modeling",
        "Pad, Pocket, Shaft & Groove",
        "Generative Shape Design (GSD)",
        "Assembly Design & Constraints",
        "Drafting & Drawing Generation",
        "Surface to Solid Conversion",
        "Capstone: Automotive Component Design",
      ],
    ),
    Course(
      title: "Android & iOS Mobile Development",
      slug: "android-ios-mobile-development",
      description: "Build modern mobile applications for Android and iOS platforms with hands-on project experience. Learn cross-platform development with Flutter/Dart, connect to real backends, and deploy to app stores.",
      imageUrl: "https://www.nlitedu.com/fontimage/iosand2.png",
      category: "PROGRAMMING",
      categoryColor: Colors.green,
      duration: "12 Weeks",
      level: "Intermediate",
      rating: 4.8,
      price: "₹999*",
      highlights: [
        "Cross-platform mobile app development",
        "Hands-on app design and deployment",
        "Build real mobile projects for your portfolio",
        "Backend integration with Firebase/Supabase",
        "State management & navigation",
        "Industry-recognized NLIT certification",
      ],
      instructorName: "Rahul Singh",
      instructorImage: "https://ui-avatars.com/api/?name=Rahul+Singh&background=22c55e&color=fff&format=png",
      totalReviews: 1400,
      syllabus: [
        "Dart Programming Language",
        "Flutter Widgets & Layouts",
        "Navigation & Routing",
        "State Management (Riverpod/Provider)",
        "Firebase Integration",
        "REST APIs & Networking",
        "App Deployment (Play Store/App Store)",
        "Capstone: Full-Stack Mobile App",
      ],
    ),
    Course(
      title: "IoT & Embedded Systems",
      slug: "iot-embedded",
      description: "Connect the physical world to the digital with hardware programming, network sensors, and embedded systems. Build functional IoT prototypes using Arduino, ESP32, and cloud connectivity.",
      imageUrl: "https://www.nlitedu.com/fontimage/iot.png",
      category: "ENGINEERING",
      categoryColor: Colors.purple,
      duration: "14 Weeks",
      level: "Advanced",
      rating: 4.9,
      price: "₹999*",
      highlights: [
        "Hardware programming and networking",
        "Sensor integration and real-time data",
        "Build functional IoT prototypes",
        "ESP32 & Arduino programming",
        "MQTT & cloud IoT platforms",
        "Industry-recognized NLIT certification",
      ],
      instructorName: "Dr. Vikram Sethi",
      instructorImage: "https://ui-avatars.com/api/?name=Vikram+Sethi&background=a855f7&color=fff&format=png",
      totalReviews: 420,
      syllabus: [
        "IoT Fundamentals & Architecture",
        "Arduino Programming & GPIO",
        "Sensors & Actuators Integration",
        "Serial Communication (UART, I2C, SPI)",
        "ESP32 & WiFi Connectivity",
        "MQTT Protocol & Cloud Platforms",
        "Real-Time Data Dashboards",
        "Capstone: Smart Home IoT System",
      ],
    ),
    Course(
      title: "NLIT Course Enrollment",
      slug: "general",
      description: "Select your course and fill out the enrollment form so we can reserve your seat and help you begin your learning journey.",
      imageUrl: "https://www.nlitedu.com/fontimage/java.png",
      category: "GENERAL",
      categoryColor: Colors.grey,
      duration: "Flexible",
      level: "All Levels",
      rating: 5.0,
      price: "Select Course",
      highlights: [
        "Choose from courses across design, development, AI, and engineering",
        "Secure admission with a simple online form",
        "Receive course guidance from the NLIT team",
      ],
      instructorName: "NLIT Team",
      instructorImage: "https://ui-avatars.com/api/?name=NLIT+Team&background=6366f1&color=fff&format=png",
      totalReviews: 5000,
      syllabus: ["General Admission"],
    ),
  ];
});
