import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/material.dart';
import '../models/course.dart';
import '../core/theme.dart';

final courseProvider = Provider<List<Course>>((ref) {
  return [
    Course(
      title: 'Java Programming',
      description: 'Learn object-oriented programming and backend fundamentals.',
      imageUrl: 'https://nlit.co.in/fontimage/java.png',
      slug: 'java-programming',
      category: 'PROGRAMMING',
      categoryColor: AppTheme.primary,
      duration: '16 Hours',
      level: 'Beginner',
    ),
    Course(
      title: 'Python Programming',
      description: 'Master Python for data science, automation, and scripting.',
      imageUrl: 'https://nlit.co.in/fontimage/python.png',
      slug: 'python-programming',
      category: 'PROGRAMMING',
      categoryColor: AppTheme.primary,
      duration: '20 Hours',
      level: 'Beginner',
    ),
    Course(
      title: 'AutoCAD',
      description: 'Design and draft 2D/3D models for engineering and architecture.',
      imageUrl: 'https://nlit.co.in/fontimage/autocad.png',
      slug: 'autocad-2d-3d-design',
      category: 'DESIGN',
      categoryColor: const Color(0xFF7743B5),
      duration: '24 Hours',
      level: 'Intermediate',
    ),
    Course(
      title: 'Revit',
      description: 'Learn building information modeling (BIM) for architecture.',
      imageUrl: 'https://nlit.co.in/fontimage/revit.jpg',
      slug: 'revit-bim',
      category: 'ENGINEERING',
      categoryColor: const Color(0xFF003A80),
      duration: '30 Hours',
      level: 'Advanced',
    ),
    Course(
      title: 'STAAD Pro',
      description: 'Structural analysis and design software for civil engineers.',
      imageUrl: 'https://nlit.co.in/fontimage/staadpro.jpg',
      slug: 'staadpro',
      category: 'ENGINEERING',
      categoryColor: const Color(0xFF003A80),
      duration: '25 Hours',
      level: 'Advanced',
    ),
    Course(
      title: 'SolidWorks',
      description: 'Mechanical design and simulation using SolidWorks CAD.',
      imageUrl: 'https://nlit.co.in/fontimage/solid2.png',
      slug: 'solidworks',
      category: 'DESIGN',
      categoryColor: const Color(0xFF7743B5),
      duration: '22 Hours',
      level: 'Intermediate',
    ),
    Course(
      title: 'CATIA',
      description: 'Advanced CAD/CAM for aerospace, automotive, and engineering.',
      imageUrl: 'https://nlit.co.in/fontimage/CATI2.png',
      slug: 'catia',
      category: 'DESIGN',
      categoryColor: const Color(0xFF7743B5),
      duration: '28 Hours',
      level: 'Advanced',
    ),
    Course(
      title: 'Android / iOS Development',
      description: 'Build mobile applications using modern frameworks.',
      imageUrl: 'https://nlit.co.in/fontimage/iosand2.png',
      slug: 'android-ios-mobile-development',
      category: 'PROGRAMMING',
      categoryColor: AppTheme.primary,
      duration: '40 Hours',
      level: 'Beginner',
    ),
    Course(
      title: 'MATLAB',
      description: 'Programming and simulation for engineering and scientific tasks.',
      imageUrl: 'https://nlit.co.in/fontimage/matlab2.png',
      slug: 'matlab-scientific-computing',
      category: 'PROGRAMMING',
      categoryColor: AppTheme.primary,
      duration: '18 Hours',
      level: 'Intermediate',
    ),
  ];
});
